### ISSUE TITLE
add complement option to complement any platform

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/github-comment#134]
.github-comment.yml

* [drone/envsubst](https://github.com/drone/envsubst)
* text/template
  * http://masterminds.github.io/sprig/strings.html

ex.

```yaml
complement:
  org: DRONE_REPO_OWNER
  repo: DRONE_REPO_NAME
  pr: DRONE_PULL_REQUEST
  revision: DRONE_COMMIT_SHA1
```

```yaml
platforms:
- name: circleci
  check:  CIRCLECI
  owner:
  repo:
  pr: '{{env "CIRCLE_PULL_REQUEST"}}'
  sha: '{{env "CIRCLE_SHA1"}}'
  build_url: '{{env "CIRCLE_BUILD_URL"}}'
```

**Comment by suzuki-shunsuke** [comment]
```yaml
complement:
  pr:
  - "CIRCLE_PULL_REQUEST"
  - CI_INFO_PR_NUMBER
  org:
  repo:
  sha1:
```

**Comment by suzuki-shunsuke** [comment]
```yaml
complement:
  pr:
  - type: envsubst
    value: "${CIRCLE_PULL_REQUEST}"
  - type: template
    value: "{{env "CIRCLE_PULL_REQUEST"}}"
```
