### ISSUE TITLE
feat: support to minimize old comments

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/github-comment#187]
## Motivation

When github-comment is used at CI, github-comment posts a comment every builds.
So many same comments are posted.
Sometimes old comments are noisy, so we want to hide them.

## How

Add a field `minimize`.
This is an [expr](https://github.com/antonmedv/expr/blob/master/docs/Language-Definition.md) expressions which existing comments is minimized.
If the comment matched to the condition, the comment is minimized.

1. Get list of pull request comments
2. Post a comment
3. If it succeeds to post a comment, remove comments which match the condition

## GitHub API

* https://docs.github.com/en/free-pro-team@latest/graphql/reference/mutations#minimizecomment
* https://docs.github.com/en/free-pro-team@latest/rest/reference/issues#list-issue-comments

## Example

```yaml
exec:
  foo:
  - when: ExitCode != 0
    template: |
      foo
    minimize: comment.body contains "foo" # minimize existing comments which includes `foo`
```
