### ISSUE TITLE
add vars to complement

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/github-comment#246]
```yaml
complement:
  vars:
    yoo:
    - type: envsubst
      value: "${YOO}"
```
