### ISSUE TITLE
How pass a variable to `-condition` option in `hide` command?

### ISSUE THREAD

**Issue by ponkio-o** [suzuki-shunsuke/github-comment#375]
Hi, Thank you for developing such a useful tool.

I have a question about the `hide` command in `github-comment`.
How do I pass a variable to the `-conditon` of the hide command?

I am also using tfcmt and would like to hide the "terraform plan" comments commented by tfcmt. It is a Monorepo configuration and uses the GitHub Actions matrix to run the "terraform plan".

The Github Actions configuration file thet we are using look something like this:
```yaml
  plan:
    name: terraform plan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        workdir:
          - work1
          - service1/envs/development
          - service1/envs/production
          - service2/envs/development
          - service2/envs/production

    concurrency:
      group: terraform-${{ matrix.workdir }}

    steps:
      ~~~

      - name: Install tfcmt
        if: steps.diff.outputs.diff
        uses: ./.github/workflows/composite/install-tfcmt

      - name: Install github-comment
        if: steps.diff.outputs.diff
        uses: ./.github/workflows/composite/install-github-comment

      - name: Hide old comment
        if: steps.diff.outputs.diff
        run : github-comment hide -condition 'Comment.HasMeta && Comment.Meta.JobName contains "plan"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform plan
        working-directory: ${{ matrix.workdir }}
        id: plan
        run: |
          if [ -n "$PR_HEAD_SHA" ]; then
            export GITHUB_SHA=$PR_HEAD_SHA
          fi
          tfcmt -owner ${GITHUB_REPOSITORY%/*} -repo ${GITHUB_REPOSITORY#*/} -pr "$PR_NUMBER" -var "target:${WORK_DIR}" plan -- terraform plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          PR_NUMBER: ${{ github.event.number }}
          WORK_DIR: ${{ matrix.workdir }}
```

In the above example, `'Comment.HasMeta && Comment.Meta.JobName contains "plan"'` is specified as the `-condition`, but with this condition, event necessary comments will be hidden depending on the timing of execution.

So I tried the following configuration.
```yaml
      - name: Hide old comment
        if: steps.diff.outputs.diff
        run : github-comment hide -condition 'Comment.HasMeta && Comment.Meta.JobName contains "plan" && Comment.Meta.Target contains ${WORK_DIR}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORK_DIR: ${{ matrix.workdir }}
```

but, occurred following error:
```
compile an expression: Comment.HasMeta && Comment.Meta.JobName contains "plan" && Comment.Meta.Target contains ${WORK_DIR}: unexpected token Bracket("{") (1:90)
 | Comment.HasMeta && Comment.Meta.JobName contains "plan" && Comment.Meta.Target contains ${WORK_DIR}
```

When I add double quotes, the error does not occur anymore, but `${WORK_DIR}` is treated as a string instead of being expanded as a variable.

```yaml
      - name: Hide old comment
        if: steps.diff.outputs.diff
        run : github-comment hide -condition 'Comment.HasMeta && Comment.Meta.JobName contains "plan" && Comment.Meta.Target contains "${WORK_DIR}"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORK_DIR: ${{ matrix.workdir }}
```

What should I do in such a case?

If there is any other information you need, please let us know.
