### ISSUE TITLE
[BUG?] `"` is not displayed correctly

### ISSUE THREAD

**Issue by ponkio-o** [suzuki-shunsuke/github-comment#513]
Hi @suzuki-shunsuke thanks for developing such a useful tool!

I found a bug in github-comment and would like to report it.

## What happend
When I posted the results of `terraform validate -no-color` with github-comment, the double quotes (`"`) were not displayed correctly. Specifically, it is converted to `&#34;`.

PR comment
![image](https://user-images.githubusercontent.com/29038315/179915244-ac75572b-0b46-4141-8cbf-285940c54186.png)

## Configuration

actions.yaml
```yaml
      - name: Terraform validate
        working-directory: ${{ matrix.workdir }}
        id: validate
        run: github-comment exec -k validate -- terraform validate -no-color
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

.github-comment.yaml
```yaml
---
exec:
  validate:
    - when: ExitCode != 0
      template: |
        ## :x: ERROR : terraform validate
        {{template "link" .}}
        ```
        {{.CombinedOutput}}```
```

## Expected behavior
```
Error: Reference to undeclared module

  on main.tf line 1118, in module "web_frontend":
1118:   alb_tg_arn = module.web_api_gateway_alb.alb_tg_arn

No module call named "web_api_gateway_alb" is declared in the root module.
```

## Other
The GitHub Actions results appear to be correct.
![image](https://user-images.githubusercontent.com/29038315/179916065-a6359d17-2969-45ab-b80e-36b5c60c6657.png)

Is this a bug on the github-comment side?
