### ISSUE TITLE
feat: support variables

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/github-comment#55]
.github-comment.yml

```yaml
---
vars:
  header: foo
post:
  default:
    - template: "{{.Vars.header}}"
```
