### ISSUE TITLE
support to configure some parameters with the configuration file

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/github-comment#60]
- Org
- Repo

```yaml
---
base:
  org: <org>
  repo: <repo>
post:
  ...
exec:
  ...
```
