### ISSUE TITLE
feat: add templates in the configuration file

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/github-comment#74]
https://play.golang.org/p/T7q_p5TxBRi

```yaml
templates:
  header: {{.Org}}
post:
  default: |
    {{template "header" .}}
```
